# Generated by Django 5.2.7 on 2025-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('customer_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('web_url', models.URLField()),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('WAITING_FOR_ANSWER', 'WAITING_FOR_ANSWER'), ('WAITING_FOR_APPROVE', 'WAITING_FOR_APPROVE'), ('ANSWERED', 'ANSWERED'), ('REPORTED', 'REPORTED'), ('REJECTED', 'REJECTED'), ('ERROR', 'ERROR')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
