# Generated by Django 5.2.7 on 2026-01-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('customer_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('web_url', models.URLField()),
                ('response', models.TextField(default='temp', max_length=5000)),
                ('status', models.CharField(choices=[('WAITING_FOR_ANSWER', 'WAITING_FOR_ANSWER'), ('WAITING_FOR_APPROVE', 'WAITING_FOR_APPROVE'), ('APPROVED', 'APPROVED'), ('ANSWERED', 'ANSWERED'), ('REPORTED', 'REPORTED'), ('REJECTED', 'REJECTED'), ('ERROR', 'ERROR')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=50)),
                ('keywords', models.TextField()),
                ('summary', models.TextField()),
                ('main_issue', models.TextField()),
                ('required_action', models.BooleanField()),
                ('response_tone', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('quality_control', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzers', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Comment Analyzer',
                'verbose_name_plural': 'Comment Analyzers',
            },
        ),
        migrations.CreateModel(
            name='CommentQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('professionalism', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('warmth', models.IntegerField()),
                ('solution_focus', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Comment Quality Score',
                'verbose_name_plural': 'Comment Quality Scores',
            },
        ),
    ]
