# Generated by Django 5.2.7 on 2025-10-12 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.TextField(default='temp', max_length=5000),
        ),
        migrations.CreateModel(
            name='CommentAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=50)),
                ('keywords', models.TextField()),
                ('summary', models.TextField()),
                ('main_issue', models.TextField()),
                ('required_action', models.BooleanField()),
                ('response_tone', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('quality_control', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzers', to='comment.comment')),
            ],
            options={
                'verbose_name': 'Comment Analyzer',
                'verbose_name_plural': 'Comment Analyzers',
            },
        ),
    ]
