# Generated by Django 5.2.7 on 2025-10-14 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_response_commentanalyzer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_ANSWER', 'WAITING_FOR_ANSWER'), ('WAITING_FOR_APPROVE', 'WAITING_FOR_APPROVE'), ('APPROVED', 'APPROVED'), ('ANSWERED', 'ANSWERED'), ('REPORTED', 'REPORTED'), ('REJECTED', 'REJECTED'), ('ERROR', 'ERROR')], max_length=50),
        ),
        migrations.CreateModel(
            name='CommentQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('professionalism', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('warmth', models.IntegerField()),
                ('solution_focus', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='comment.comment')),
            ],
            options={
                'verbose_name': 'Comment Quality Score',
                'verbose_name_plural': 'Comment Quality Scores',
            },
        ),
    ]
