AGENT_STATUS = [
    ('WAITING_FOR_ANSWER', 'WAITING_FOR_ANSWER'),
    ('WAITING_FOR_APPROVE', 'WAITING_FOR_APPROVE'),
    ('APPROVED', 'APPROVED'),
    ('ANSWERED', 'ANSWERED'),
    ('REPORTED', 'REPORTED'),
    ('REJECTED', 'REJECTED'),
    ('ERROR', 'ERROR'),
]
